dist: xenial
language: rust
rust:
  - nightly
  - beta
  - 1.39.0 # minimum supported version
  - stable
addons:
  apt:
    packages:
    - libgtk-3-dev
    - libmount-dev
env:
  - GTK=3.96
script:
  - ./build_travis.sh
